#!/bin/bash


# ================= for CentOS ==================


#filename=stats

#: > $filename

#for procdir in /proc/[0-9]*
#do
#    pid="$(basename "$procdir")" &&
#    ppid="$(awk '{if ($1 == "PPid:") print $2}' "$procdir"/status 2>/dev/null)" &&
#    runtime="$(awk '{if ($1 == "se.sum_exec_runtime") print $3}' "$procdir"/sched 2>/dev/null)" &&
#    switches="$(awk '{if ($1 == "nr_switches") print $3}' "$procdir"/sched 2>/dev/null)" &&
#    art="$(echo "$runtime $switches" | awk '{printf "%.3f", $1/$2}' -)" &&
#    printf "ProccessID=%i : Parent_ProcessID=%i : Average_Running_time=%f\n"\
#            "$pid" "$ppid" "$art" >> "$filename"
#done
#tmpfile=$(mktemp)
#sort -n -k 3.19 "$filename" > "$tmpfile"
#cat "$tmpfile" > "$filename"

filename=stats

: > $filename

for procdir in /proc/[0-9]*
do
    pid="$(basename "$procdir")" &&
    ppid="$(awk '{if ($1 == "PPid:") print $2}' "$procdir"/status 2>/dev/null)" &&
    runtime="$(awk '{if ($1 == "se.sum_exec_runtime") print $3}' "$procdir"/sched 2>/dev/null)" &&
    switches="$(awk '{if ($1 == "nr_switches") print $3}' "$procdir"/sched 2>/dev/null)" &&
    art="$(echo "$runtime $switches" | awk '{printf "%.3f", $1/$2}' -)" &&
    printf "ProccessID=%i : Parent_ProcessID=%i : Average_Running_time=%f\n"\
            "$pid" "$ppid" "$art" >> "$filename"
done
tmpfile=$(mktemp)
sort -n -k 3.19 "$filename" > "$tmpfile"
cat "$tmpfile" > "$filename"
