events {}

http {
    server {
        listen 80;
        server_name 10.101.1.25;

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name 10.101.1.25;

        ssl_certificate     /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        location / {
            proxy_pass http://10.101.1.26:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api {
            proxy_pass http://10.101.1.26:3001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
